# Generated by Django 2.1.8 on 2020-12-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=5)),
                ('status', models.CharField(max_length=20)),
                ('ment', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
