# Generated by Django 2.1.8 on 2020-12-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='created_at',
        ),
    ]
