# Generated by Django 2.1.8 on 2020-12-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_remove_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.TextField(),
        ),
    ]
