# Generated by Django 3.1.4 on 2020-12-27 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20201227_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='hashtag',
        ),
        migrations.DeleteModel(
            name='HashTag',
        ),
    ]
