# Generated by Django 3.1.4 on 2020-12-27 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_auto_20201227_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='ment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='person',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
